name: Jadwal

on:
  schedule:
    # Pada tanggal ke-1 dan ke-15
    - cron: '0 0 1,15 * *'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Menyiapkan Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Menginstal paket
        run: gem install awesome_bot
      - name: Memeriksa pranala luar pada berkas README
        run: awesome_bot README.md --white-list duckduckgo.com
